config/routes.rb
Rails.application.routes.draw do
  resources :addresses
    get '/s/:name' => "addresses#forward_user", :as => :forward_user
    
    root "addresses#index"
    

end

app/models/address.rb
class Address < ActiveRecord::Base
    validates_uniqueness_of :name
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
    def index
        @addresses = Address.all
        @address = Address.new
    end
    
    def forward_user
        @address = Address.find_by_name(params[:name])
            @address.clicks = @address.clicks + 1
            @address.save
        redirect_to @address.location
    end
    
    def new
        @address = Address.new
    end
    
    def create
        @address = Address.new(params.require(:address).permit(:location, :name))
        if @address.save
            redirect_to root_path
        else
            render action: "new"
        end
    end
    
    def show
        @address = Address.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/index.html.erb
<div class="navbar-margin">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand">Short!</a>
                </div>
                <div class="nav navbar-nav navbar-right inline">
                    <%= form_for @address do |form| %>
                    <div class="forms">
                        <%= form.text_field :name, placeholder: "Name" %>
                        <%= form.text_field :location, placeholder: "Full url" %>
                        <p class="forms"><%= form.submit "Shorten it!", class: "btn btn-primary" %></p>
                    </div>
                    <% end %>
                </div>
            </div>
        </nav>
    </div>

    <div style="background:red; color: white; font-weight: bold">
      <% @address.errors.full_messages.each do |message| %>
        <%= message %><br>
      <% end %>
    </div>

    <div class="container">
    </div>

<h2>Recently Shortened URLs</h2>
 
<table class="table table-striped">
  <thead>
  <th>Short URL</th>
  <th>Long URL</th>
  <th>Clicks</th>
  </thead>
  <tbody>
  <% @addresses.each do |address| %>
    <tr>
      <td><%= link_to forward_user_url(name: address.name), forward_user_url(name: address.name) %></td>
      <td><%= address.location %></td>
      <td><%= address.clicks %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/addresses/new.html.erb
<h2>Create a shorter URL</h2>

<div style="background:red; color: white; font-weight: bold">
  <% @address.errors.full_messages.each do |message| %>
    <%= message %><br>
  <% end %>
</div>

<%= link_to "Go back", root_path %>

<!--
<%= form_for @address do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
 
  <div>
    <%= form.label :location, "Location - must start with http://" %><br>
    <%= form.text_field :location %>
  </div>
 
  <p><%= form.submit "Shorten it!" %></p>
<% end %>-->

app/views/addresses/show.html.erb
<h2>Your new short URL</h2>
<%= forward_user_url(name: @address.name) %> will redirect to <%= @address.location %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShortUrl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div id="fb-root"></div>
        <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
                fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
        </script>

<%= yield %>   
    
    
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4">
                <div class="fb-like"></div>
                <a href="https://twitter.com/share" class="twitter-share-button" data-via="_hannahkoala">Tweet</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>

    
</body>
</html>